// web/src/components/Dropdown.tsx
import React, {
  useState,
  ReactElement,
  useEffect,
  PropsWithChildren,
} from "react";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import Icon from "./Icon/Icon";
import styled from "styled-components";

interface Props {
  label: string;
  icon?: IconDefinition;
}

const HoverOverlay = styled.div`
  position: relative;

  &::after {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    opacity: 0;
    background: var(--overlay);
    transition: opacity 0.1s;
    pointer-events: none;
    border-radius: inherit;
  }

  &:hover::after {
    opacity: 1;
  }
`;

const spacingOuter = "2rem";
const width = "200px";
const borderRadius = "2px";
const transitionDuration = "0.1ms";

const Root = styled.div`
  position: relative;
  width: ${width};
  height: 48px;
  cursor: pointer;
`;

const Current = styled(HoverOverlay)`
  position: relative;
  display: flex;
  align-items: center;
  z-index: 1;
  padding: 0 ${spacingOuter};
  border: 1px solid var(--colorSeparator);
  border-radius: 24px;
  width: 100%;
  height: 100%;
`;

const Label = styled.span<{ extraMargin: boolean }>`
  width: 100%;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
  color: inherit;
  margin: 0 ${(props) => (props.extraMargin ? spacingOuter : 0)} 0 0;
`;

const OptionsWrapper = styled.div<{ expanded: boolean }>`
  position: absolute;
  right: 0;
  visibility: ${(props) => (props.expanded ? "visible" : "hidden")};
  top: calc(100% + 1rem);
  min-width: ${width};
  border-top: 0;
  background: var(--colorElevationHigh);
  box-shadow: var(--dropShadowElevationHigh);
  opacity: ${(props) => (props.expanded ? 1 : 0)};
  border-radius: ${borderRadius};
  transition: opacity ${transitionDuration},
    visibility 0s ${(props) => (props.expanded ? 0 : transitionDuration)};
  z-index: 99;
`;

const Triangle = styled.span`
  width: 1rem;
  height: 1rem;
  background: var(--colorElevationHigh);
  position: absolute;
  top: -0.5rem;
  right: ${spacingOuter};
  transform: rotate(45deg);
`;

const Options = styled.div`
  overflow: hidden;
  border-radius: ${borderRadius};
`;

function Dropdown({
  label,
  icon,
  children,
}: PropsWithChildren<Props>): ReactElement {
  const [expanded, setExpanded] = useState(false);

  const handleOutsideClick = () => setExpanded(false);

  const toggle = () => setExpanded(!expanded);

  useEffect(() => {
    window.addEventListener("click", handleOutsideClick);

    return () => {
      window.removeEventListener("click", handleOutsideClick);
    };
  }, []);

  return (
    <Root
      onClick={(e) => {
        e.stopPropagation();
        toggle();
      }}
    >
      <Current>
        <Label extraMargin={!!icon}>{label}</Label>
        {icon && <Icon icon={icon} />}
      </Current>
      <OptionsWrapper expanded={expanded}>
        <Triangle />
        <Options>{children}</Options>
      </OptionsWrapper>
    </Root>
  );
}

export default Dropdown;

// src/components/Dropdown.vue
<template>
  <div class="dropdown" :class="{ expanded: isExpanded, 'has-icon': !!icon }" @click.stop="toggle">
    <div class="current">
      <span class="label">{{ label }}</span>
      <b-icon v-if="icon" class="icon" :icon="icon" size="is-small" />
    </div>
    <div class="options">
      <span class="triangle" />

      <div class="options-items">
        <slot />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";

@Component({
  name: "Dropdown"
})
export default class Dropdown extends Vue {
  @Prop({ required: true })
  readonly label!: string;

  @Prop()
  readonly icon!: string;

  isExpanded = false;

  mounted() {
    window.addEventListener("click", this.handleOutsideClick);
  }

  beforeDestroy() {
    window.removeEventListener("click", this.handleOutsideClick);
  }

  selectOption(value: string) {
    this.$emit("change", value);

    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }

  handleOutsideClick() {
    this.isExpanded = false;
  }
}
</script>

<style lang="scss" scoped>
$colorPrimary: #0f4c5c;
$spacingOuter: 1rem;
$spacingInner: 0.5rem;
$transitionDuration: 0.2s;
$width: 200px;
$borderRadius: 4px;

.dropdown {
  position: relative;
  width: $width;
  height: 48px;
  cursor: pointer;

  &.expanded {
    .current {
      .caret {
        transform: rotate(180deg);
      }
    }

    .options {
      visibility: visible;
      opacity: 1;
      transition: opacity $transitionDuration, visibility 0s;
    }
  }

  &.has-icon {
    .current .label {
      margin: 0 $spacingOuter 0 0;
    }
  }

  .current {
    display: flex;
    align-items: center;
    z-index: 1;
    padding: $spacingOuter;
    background: $colorPrimary;
    border-radius: $borderRadius;
    color: #fff;
    width: 100%;

    .icon {
      color: inherit;
    }

    .label {
      width: 100%;
      white-space: nowrap;
      text-overflow: ellipsis;
      overflow: hidden;
      color: inherit;
      margin: 0;
    }
  }

  .options {
    position: absolute;
    right: 0;
    visibility: hidden;
    top: calc(100% + 24px);
    min-width: $width;
    border-top: 0;
    background: #fff;
    box-shadow: 0 0 1rem rgba(#222, 0.4);
    opacity: 0;
    border-radius: $borderRadius;
    transition: opacity $transitionDuration, visibility 0s $transitionDuration;

    .triangle {
      width: $spacingOuter;
      height: $spacingOuter;
      background: #fff;
      position: absolute;
      top: $spacingOuter * -0.5;
      right: $spacingOuter;
      transform: rotate(45deg);
    }

    .options-items {
      overflow: hidden;
      border-radius: $borderRadius;
    }
  }
}
</style>
